In [ ]:
# Data Ingestion, Understanding, first cleaning ideas

In [1]:
from pathlib import Path
import sys

# Bootstrap: make project package importable from notebook
NOTEBOOK_PROJECT_ROOT = Path.cwd().parent
SRC_DIR = NOTEBOOK_PROJECT_ROOT / "03_src"

if str(SRC_DIR) not in sys.path:
    sys.path.append(str(SRC_DIR))

# Imports from project package
from chatgpt_reviews.paths import PROJECT_ROOT, DATA_DIR, RAW_DIR
from chatgpt_reviews.project_io import (
    read_csv_from_raw,
    write_csv_to_processed,
    read_csv_from_processed,
)

# Dataset accessed and saved on June 20 2026
df = read_csv_from_raw("chatgpt_reviews.csv")

In [ ]:
# Data overview using data_overview module

from chatgpt_reviews.data_overview import data_overview

overview = data_overview(df)

Shape: 1,089,749 rows × 8 columns

Top 3 rows (quick peek):

,reviewId,userName,content,score,thumbsUpCount,reviewCreatedVersion,at,appVersion
0,d864ac78-952a-42a3-b555-aa0e7b7127e0,Mohammad Shamim,this app is very helpful. every person.,5,0,1.2026.160,2026-06-19 09:13:05,1.2026.160
1,026cd749-29e3-4956-9a97-a6241c81b95c,Ganesh Pathukula,Note a clear phot photos,3,0,1.2026.160,2026-06-19 09:12:45,1.2026.160
2,d2d65308-2060-45d5-8cd5-f1fd4902814c,Gorle Chandrarao,exlent,4,0,1.2026.160,2026-06-19 09:12:45,1.2026.160

Dtypes (sorted by column name):

appVersion                str
at                        str
content                   str
reviewCreatedVersion      str
reviewId                  str
score                   int64
thumbsUpCount           int64
userName                  str
dtype: object

Numeric summary (describe):

                   count      mean        std  min  25%  50%  75%      max
score          1089749.0  4.489588   1.115183  1.0  5.0  5.0  5.0      5.0
thumbsUpCount  1089749.0  0.150726  21.454611  0.0  0.0  0.0  0.0  20679.0

Top 15 missingness:

appVersion              0.072350
reviewCreatedVersion    0.072350
content                 0.000016
userName                0.000002
score                   0.000000
reviewId                0.000000
thumbsUpCount           0.000000
at                      0.000000
Name: missing_rate, dtype: float64

Top 15 unique counts:

reviewId                1079449
at                      1063231
userName                 901635
content                  521910
thumbsUpCount               290
reviewCreatedVersion        174
appVersion                  174
score                         5
Name: n_unique, dtype: int64

Duplicated rows: 2509

Categorical preview (top 10 levels) for up to 8 columns:
  • reviewId

reviewId
b19b8c98-712b-4167-8a7b-362eeee188e9    40
7eb8ba7d-3f52-4080-96c8-6b15e5ab6483    35
5690a8c6-007a-49e7-977c-38d58698fe88    14
a1b15076-b336-4d3f-8296-9a02765dc7d2    14
52382614-bd16-4e45-bd48-e612f675bc45    13
776417d4-bde4-44cc-ad88-395b2182a456    12
c30f6c4a-bc60-44c1-8b90-61e6627caae6    12
53bfe3a4-c9ca-4822-b1b2-9bde3d46fa93    11
e3d02e61-c17a-4218-94e4-e0917edd281d    10
e4c800c7-3971-40ec-bb51-bd71f282cc99    10
Name: count, dtype: int64

  • userName

userName
Rahul Kumar      377
A Google user    344
Amit Kumar       340
Deepak Kumar     339
Rohit Kumar      315
Manish Kumar     305
Prince Kumar     295
Ajay Kumar       286
Ravi Kumar       282
Raj Kumar        279
Name: count, dtype: int64

  • content

content
good         84443
nice         33522
very good    16824
best         12716
super        12496
excellent    11089
Good         10887
good app      7709
nice app      7574
good 👍        7227
Name: count, dtype: int64

  • reviewCreatedVersion

reviewCreatedVersion
NaN           78843
1.2025.084    43421
1.2026.125    27350
1.2025.154    25630
1.2024.352    25487
1.2025.091    21643
1.2025.350    20471
1.2025.105    19995
1.2025.175    18765
1.2024.268    16677
Name: count, dtype: int64

  • at

at
2024-05-12 08:41:31    12
2024-05-12 05:55:09    12
2023-07-25 15:10:04     8
2024-05-17 08:02:13     6
2024-05-17 02:52:26     6
2024-05-12 08:52:10     6
2024-05-12 08:51:46     6
2024-05-12 08:49:39     6
2024-05-12 08:47:24     6
2024-05-12 08:46:56     6
Name: count, dtype: int64

  • appVersion

appVersion
NaN           78843
1.2025.084    43421
1.2026.125    27350
1.2025.154    25630
1.2024.352    25487
1.2025.091    21643
1.2025.350    20471
1.2025.105    19995
1.2025.175    18765
1.2024.268    16677
Name: count, dtype: int64

In [3]:
df.columns.tolist

<bound method IndexOpsMixin.tolist of Index(['reviewId', 'userName', 'content', 'score', 'thumbsUpCount',
       'reviewCreatedVersion', 'at', 'appVersion'],
      dtype='str')>

In [5]:
display(df.head())
display(df.tail())

,reviewId,userName,content,score,thumbsUpCount,reviewCreatedVersion,at,appVersion
0,d864ac78-952a-42a3-b555-aa0e7b7127e0,Mohammad Shamim,this app is very helpful. every person.,5,0,1.2026.160,2026-06-19 09:13:05,1.2026.160
1,026cd749-29e3-4956-9a97-a6241c81b95c,Ganesh Pathukula,Note a clear phot photos,3,0,1.2026.160,2026-06-19 09:12:45,1.2026.160
2,d2d65308-2060-45d5-8cd5-f1fd4902814c,Gorle Chandrarao,exlent,4,0,1.2026.160,2026-06-19 09:12:45,1.2026.160
3,b6428cd3-7d04-49cd-90bd-7cfbb5592268,Rakib Sany,Good,5,0,1.2026.160,2026-06-19 09:12:36,1.2026.160
4,835c77c7-7a6c-4183-886e-2955f1a1f895,Priti Kumari,nice🤩,5,0,1.2026.160,2026-06-19 09:12:32,1.2026.160

,reviewId,userName,content,score,thumbsUpCount,reviewCreatedVersion,at,appVersion
1089744,462686ff-e500-413c-a6b4-2badc2e3b21d,m.santhosh Kumar,Update 2023,5,0,NaN,2023-07-27 16:26:31,NaN
1089745,f10e0d48-ecb6-42db-b103-46c0046f9be9,Andrew Bourgeois,its grear,5,0,NaN,2023-09-23 16:25:18,NaN
1089746,df909a49-90b5-4dac-9b89-c4bd5a7c2f75,Dern Bob,Funtastic App,5,0,NaN,2023-11-08 13:57:14,NaN
1089747,abe43878-973f-4e96-a765-c4af5c7f7b20,Abdur rahman arif,hi all,5,0,NaN,2023-07-25 15:32:57,NaN
1089748,0151001d-b81c-41b5-8927-f56738989625,Tushar Deran,expert application,5,0,NaN,2023-11-30 18:11:41,NaN

In [7]:
df.isna().sum().sort_values(ascending = False)

appVersion              78843
reviewCreatedVersion    78843
content                    17
userName                    2
score                       0
reviewId                    0
thumbsUpCount               0
at                          0
dtype: int64